---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-tail-log
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 10Mi
