language: generic
services:
- docker
env:
  global:
  - DOCKER_USERNAME=cpantestersbot
  - DOCKER_IMAGE_NAME=cpantesters/base
  - DOCKER_VERSION_TAG=${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_NUMBER}
  - secure: Y+RtHRiis110/t5q9PGI9g9TxjwVZF/2gW87NEZwdI2F+FYyXcu9UUdRCtrG/eSYvOfaTeCKcD00qmtlHbA/eS0JMSF8dGRQYbMl9QbHHSp4h//O7Bt5hNBk9ckCMHPOPdDSfaTjd0M1F2U4LmRkBlNk7bRe+Yim67xX7yx96Xsn0kDX5HGoWRORLj7iPGvB/HGsjfEeQ6JQWBvHtnb3Yi6emNE4M5U6PbO75JV3JjitzY/hzmpqs6LDDyiBu6yZi8GO3hheRzWLvjEUyZkZlUSJI4CRaUOQf+6tzH28nbe+Eh8OhPTo2aqWn9DC/5DKKt/S3P5hGFryAN7zh6Tu3eRJoCUKEsF2R2I06PrmKIJEA7p/JzFVDnOGt2bZW66grJ+fhQhtPMVMpqlkHn9/U2GJ6r/TzjcmdlIFcHGVC4J7fHNZ5DGzcb6jDjVajCBMxRscYjljM8iOM3GP4EhpVdHSRjTui0/lY5M2FMUGC32pMGqEqwkReUrIMa//0z1vxeON6kIDFNLuBJsWzN6Txkh9gV3vHZg75BeoJmEgiQYbB3wyp7a1Cub058AAuhUiT1iouwSCrKZxdPke3IXm1blhdPHNURySXgD0qukPWD7MtvV/rUklCrltdudgQuprqaBNbnTVeYmHBfQycTEi9RIvnvq35dYNpGWpftY6J9A=
before_install:
- docker pull "$DOCKER_IMAGE_NAME" || true
install:
- docker build --pull --cache-from "$DOCKER_IMAGE_NAME"
  --tag $DOCKER_IMAGE_NAME --tag $DOCKER_VERSION_TAG .;
deploy:
- provider: script
  skip_cleanup: true
  on:
    branch: master
  script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push $DOCKER_IMAGE_NAME
