FROM cpantesters/schema
RUN apt-get update && apt-get install -y default-mysql-client
COPY etc/docker/deploy-db.sh /app/deploy-db.sh
COPY etc/docker/mysql.conf /root/.cpanstats.cnf
COPY var/schema/metabase-schema.sql /app/metabase-schema.sql
COPY var/schema/legacy-schema.sql /app/legacy-schema.sql
RUN chmod +x deploy-db.sh
CMD [ './deploy-db.sh' ]
