services:
  api:
    image: docker.io/cpantesters/api
    command: ./bin/cpantesters-api prefork -I 30 -H 300 2>&1
    environment:
      BEAM_MINION: file:///app/etc/beam-minion.yml
      MOJO_LOG_LEVEL: debug
      MOJO_HOME: /app
      MOJO_CONFIG: /app/api.conf
      MOJO_LOG_SHORT: 1 # Remove timestamps from Mojo, added by log svc
      MOJO_INACTIVITY_TIMEOUT: 300
      MOJO_HEARTBEAT_INTERVAL: 30
      MOJO_HEARTBEAT_TIMEOUT: 300
      MOJO_PUBSUB_EXPERIMENTAL: 1 # Shut up
      MOJO_MAX_MESSAGE_SIZE: 33554432 # approx 32M
    ports:
      - 8000:3000
    configs:
      - source: api_conf
        target: /app/api.conf
    secrets:
      - mysql_cnf
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure

  legacy-metabase:
    image: docker.io/cpantesters/api
    command: cpantesters-legacy-metabase prefork -w 20 -G 1500 -H 300 2>&1
    environment:
      BEAM_MINION: file:///app/etc/beam-minion.yml
      MOJO_LOG_LEVEL: debug
      MOJO_HOME: /app
      MOJO_CONFIG: /app/metabase.conf
      MOJO_LOG_SHORT: 1 # Remove timestamps from Mojo, added by log svc
      MOJO_INACTIVITY_TIMEOUT: 300
      MOJO_HEARTBEAT_INTERVAL: 30
      MOJO_PUBSUB_EXPERIMENTAL: 1 # Shut up
      MOJO_MAX_MESSAGE_SIZE: 33554432 # approx 32M
    ports:
      - 8250:3000
    configs:
      - source: metabase_conf
        target: /app/metabase.conf
    secrets:
      - mysql_cnf
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure

  backend:
    image: docker.io/cpantesters/backend
    command: beam minion worker -j 12 -s 0
    environment:
      BEAM_MINION: file:///app/etc/beam-minion.yml
      MOJO_LOG_LEVEL: debug
    configs:
      - source: backend_db
        target: /app/etc/container/db.yml
      - source: beam_minion
        target: /app/etc/beam-minion.yml
      - source: backend_log
        target: /app/etc/container/log.yml
    secrets:
      - mysql_cnf
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          cpus: "6"
          memory: 4G

configs:
  backend_db:
    file: ./etc/container/db.yml
  beam_minion:
    file: ./etc/cpantesters-backend/beam-minion.yml
  backend_log:
    file: ./etc/container/log.yml
  api_conf:
    file: ./metabase.conf
  metabase_conf:
    file: ./metabase.conf

secrets:
  mysql_cnf:
    file: ./mysql.cnf.ini
