# This is `api.cpantesters.org`, the Mojolicious API server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: api
      labels:
        app: api
    spec:
      volumes:
        - name: conf-volume
          configMap:
            name: api-conf
            items:
              - key: api-conf
                path: api.conf
        - name: etc-volume
          configMap:
            name: etc
            items:
              - key: beam-minion
                path: beam-minion.yml
        - name: mysql-secret
          secret:
            secretName: mysql-secret

      containers:
        - name: api
          image: cpantesters/api:latest
          command:
            - cpantesters-api
            - prefork
            - -w
            - "2"
            - -I
            - "30"
            - -H
            - "300"
          env:
            - name: BEAM_MINION
              value: file:///etc/minion/beam-minion.yml
            - name: BEAM_PATH
              value: /etc/container
            - name: MOJO_LOG_LEVEL
              value: debug
            - name: MOJO_HOME
              value: /app
            - name: MOJO_MODE
              value: production
            - name: MOJO_CONFIG
              value: /etc/app/api.conf
            - name: MOJO_LOG_SHORT
              value: "1"
            - name: MOJO_INACTIVITY_TIMEOUT
              value: "300"
            - name: MOJO_HEARTBEAT_INTERVAL
              value: "30"
            - name: MOJO_PUBSUB_EXPERIMENTAL
              value: "1"
            - name: MOJO_MAX_MESSAGE_SIZE
              value: "33554432" # approx 32M
            - name: OTEL_SERVICE_NAME
              value: "api"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://signoz-install-otel-collector.telemetry.svc:4318"
          volumeMounts:
            - mountPath: /etc/app
              name: conf-volume
            - mountPath: /etc/minion
              name: etc-volume
            - mountPath: /etc/secrets
              name: mysql-secret
              readOnly: true
          resources:
            requests:
              cpu: 0.05
              memory: 300M
            limits:
              cpu: 0.1
              memory: 350M
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 3000
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: api
  namespace: default
spec:
  rules:
    - host: api.cpantesters.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
