# This defines a mysql defaults file that is referred to by various DBI DSNs
# to connect to the MySQL server.
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  mysql_cnf: ICAgIFtiYWNrZW5kXQogICAgaG9zdCA9IGRiLXByaW1hcnktMS5jcGFudGVzdGVycy5vcmcKICAgIGRhdGFiYXNlID0gY3BhbnN0YXRzCiAgICB1c2VyID0gY3BhbnRlc3RlcnMKICAgIHBhc3N3b3JkID0gTWQ1c3lNeGRzS2NmNm42ZUsKCiAgICBbd2ViXQogICAgaG9zdCA9IGRiLXByaW1hcnktMS5jcGFudGVzdGVycy5vcmcKICAgIGRhdGFiYXNlID0gY3BhbnN0YXRzCiAgICB1c2VyID0gY3BhbnRlc3RlcnMKICAgIHBhc3N3b3JkID0gTWQ1c3lNeGRzS2NmNm42ZUsK
