apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helmcharts.cattle.io/managed-by: helm-controller
  finalizers:
    - wrangler.cattle.io/on-helm-chart-remove
  generation: 1
  name: signoz-install
  namespace: kube-system
spec:
  version: 0.104.1
  chart: signoz
  repo: https://charts.signoz.io
  failurePolicy: abort
  targetNamespace: telemetry
  createNamespace: true
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helmcharts.cattle.io/managed-by: helm-controller
  finalizers:
    - wrangler.cattle.io/on-helm-chart-remove
  generation: 1
  name: signoz-k8s-infra
  namespace: kube-system
spec:
  version: 0.15.0
  chart: k8s-infra
  repo: https://charts.signoz.io
  failurePolicy: abort
  targetNamespace: telemetry
  createNamespace: true
  valuesContent: |-
    global:
      cloud: others
      clusterName: cpantesters
      deploymentEnvironment: production
    otelCollectorEndpoint: signoz-install-otel-collector.telemetry.svc:4317
    otelInsecure: true
    presets:
      otlpExporter:
        enabled: true
      loggingExporter:
        enabled: true
      logsCollection:
        blacklist:
          enabled: false
    otelDeployment:
      additionalEnvs:
        MYSQL_USERNAME:
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        MYSQL_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      config:
        receivers:
          mysql:
            endpoint: db-primary-1.cpantesters.org:3306
            username: ${env:MYSQL_USERNAME}
            password: ${env:MYSQL_PASSWORD}
            collection_interval: 10s
            initial_delay: 1s
            statement_events:
              digest_text_limit: 120
              time_limit: 24h
              limit: 250
            # We're using this to replace PMM, so we need a bunch
            # of the currently-disabled metrics
            events:
              db.server.top_query:
                enabled: true
            metrics:
              mysql.client.network.io:
                enabled: true
              mysql.commands:
                enabled: true
              mysql.connection.count:
                enabled: true
              mysql.connection.errors:
                enabled: true
              mysql.joins:
                enabled: true
              mysql.query.client.count:
                enabled: true
              mysql.query.count:
                enabled: true
              mysql.query.slow.count:
                enabled: true
              mysql.statement_event.count:
                enabled: true
              mysql.statement_event.wait.time:
                enabled: true
              mysql.table.lock_wait.read.count:
                enabled: true
              mysql.table.lock_wait.read.time:
                enabled: true
              mysql.table.lock_wait.write.count:
                enabled: true
              mysql.table.lock_wait.write.time:
                enabled: true
              mysql.table.rows:
                enabled: false
              mysql.table.size:
                enabled: false

        processors:
          resource:
            attributes:
              - key: service.name
                value: "mysql"
                action: upsert

        service:
          pipelines:
            metrics/internal:
              receivers: [mysql]
              processors: [resource, batch]
              exporters: [otlp]
